package com.presyohan.app

import org.dhatim.fastexcel.reader.ReadableWorkbook
import java.io.InputStream

/**
 * Parses .xlsx files exported by the Presyohan website (ExportPricelistModal).
 *
 * Expected Excel layout (generated by the website):
 *   Row 1: "Presyohan"                                     ← title (skip)
 *   Row 2: "Store: {name} — Branch: {branch}"              ← store info (skip)
 *   Row 3: "Exported by: ...  |  Exported at: ..."         ← meta (skip)
 *   Row 4: (blank)                                         ← spacer (skip)
 *   Row 5: Category | Name | Description | Unit | Price    ← HEADER ROW
 *   Row 6+: data rows
 *
 * The parser scans the first 25 rows for the header row (must contain at least
 * "name" and "price" column labels), then reads all rows after it as data.
 * This makes it compatible with both the Presyohan export format and generic
 * pricelist spreadsheets that have a plain header on row 1.
 */
object ExcelImportParser {

    init {
        try {
            System.setProperty("javax.xml.stream.XMLInputFactory", "com.fasterxml.aalto.stax.InputFactoryImpl")
            System.setProperty("javax.xml.stream.XMLOutputFactory", "com.fasterxml.aalto.stax.OutputFactoryImpl")
            System.setProperty("javax.xml.stream.XMLEventFactory", "com.fasterxml.aalto.stax.EventFactoryImpl")
        } catch (e: Exception) {
            android.util.Log.e("ExcelImportParser", "Failed to set StAX system properties", e)
        }
    }

    // Recognized column aliases (lowercase)
    private val ALIASES = mapOf(
        "category"    to setOf("category", "cat"),
        "name"        to setOf("name", "product", "item", "item name"),
        "price"       to setOf("price", "amount", "cost"),
        "unit"        to setOf("unit", "units", "uom", "size"),
        "description" to setOf("description", "desc", "details")
    )

    fun parseXlsx(inputStream: InputStream): List<DraftCategory> {
        val flatItems = mutableListOf<DraftItem>()

        try {
            ReadableWorkbook(inputStream).use { workbook ->
                val sheet = workbook.firstSheet
                sheet.openStream().use { stream ->

                    // Collect all rows so we can do a header-scan pass first
                    val allRows = mutableListOf<Pair<Int, List<String>>>()
                    stream.forEach { row ->
                        val cells = (0 until row.cellCount).map {
                            row.getCell(it)?.rawValue?.trim() ?: ""
                        }
                        allRows.add(row.rowNum to cells)
                    }

                    // --- Header detection (scan first 25 rows) ---
                    var colCategory    = -1
                    var colName        = -1
                    var colPrice       = -1
                    var colUnit        = -1
                    var colDescription = -1
                    var headerRowNum   = -1

                    for ((rowNum, cells) in allRows.take(25)) {
                        if (cells.all { it.isBlank() }) continue

                        val tempCols = mutableMapOf<String, Int>()
                        cells.forEachIndexed { idx, text ->
                            val t = text.lowercase().trim()
                            for ((key, aliases) in ALIASES) {
                                if (aliases.contains(t) && !tempCols.containsKey(key)) {
                                    tempCols[key] = idx
                                }
                            }
                        }

                        // Require at least "name" + "price" to call it a header row
                        if (tempCols.containsKey("name") && tempCols.containsKey("price")) {
                            colCategory    = tempCols["category"]    ?: -1
                            colName        = tempCols["name"]        ?: -1
                            colPrice       = tempCols["price"]       ?: -1
                            colUnit        = tempCols["unit"]        ?: -1
                            colDescription = tempCols["description"] ?: -1
                            headerRowNum   = rowNum
                            break
                        }
                    }

                    if (headerRowNum == -1) {
                        // Fallback: assume Presyohan column order (Cat, Name, Desc, Unit, Price)
                        android.util.Log.w("ExcelImportParser",
                            "No recognized header row found; using fallback column positions.")
                        colCategory    = 0
                        colName        = 1
                        colDescription = 2
                        colUnit        = 3
                        colPrice       = 4
                        // Start from the first non-empty row
                        headerRowNum   = (allRows.firstOrNull { (_, cells) ->
                            cells.any { it.isNotBlank() }
                        }?.first ?: 0) - 1
                    }

                    // --- Parse data rows (everything AFTER the header row) ---
                    for ((rowNum, cells) in allRows) {
                        if (rowNum <= headerRowNum) continue
                        if (cells.all { it.isBlank() }) continue
                        parseRow(
                            cells, colCategory, colName, colPrice,
                            colUnit, colDescription, rowNum, flatItems
                        )
                    }
                }
            }
        } catch (e: Exception) {
            android.util.Log.e("ExcelImportParser", "Failed to parse excel", e)
            throw e // Re-throw so the caller can surface a user-facing message
        }

        // Group flat items by category
        val categoriesMap = mutableMapOf<String, MutableList<DraftItem>>()
        for (item in flatItems) {
            val catName = item.categoryName.trim().uppercase().ifBlank { "UNCATEGORIZED" }
            categoriesMap.getOrPut(catName) { mutableListOf() }
                .add(item.copy(categoryName = catName))
        }

        return categoriesMap.map { (catName, items) ->
            DraftCategory(
                draftCategoryId = "category-${java.util.UUID.randomUUID()}",
                name = catName,
                items = items
            )
        }
    }

    private fun parseRow(
        cells: List<String>,
        colCategory: Int,
        colName: Int,
        colPrice: Int,
        colUnit: Int,
        colDescription: Int,
        rowNum: Int,
        outList: MutableList<DraftItem>
    ) {
        val category = safeCell(cells, colCategory).ifBlank { "UNCATEGORIZED" }
        val name     = safeCell(cells, colName)
        val priceRaw = safeCell(cells, colPrice)
        val unit     = safeCell(cells, colUnit).ifBlank { "1pc" }
        val description = safeCell(cells, colDescription).ifBlank { null }

        // Skip completely empty rows
        if (name.isBlank() && priceRaw.isBlank()) return

        // Price cell from the Presyohan export is a real number stored with ₱ currency
        // formatting, so rawValue from fastexcel gives us the plain numeric string.
        // However, plain-text or manually crafted files may include the ₱ symbol or
        // comma thousand-separators — strip all of those before parsing.
        val priceClean = priceRaw
            .replace("₱", "")
            .replace("PHP", "", ignoreCase = true)
            .replace(",", "")   // strip thousand separators  e.g. "1,250.00" → "1250.00"
            .trim()
        val priceVal = priceClean.toDoubleOrNull()

        val errors = mutableListOf<ValidationError>()
        var status = ValidationStatus.NEW

        if (name.isBlank()) {
            errors.add(ValidationError.EMPTY_PRODUCT_NAME)
            status = ValidationStatus.INVALID
        }
        if (priceVal == null) {
            errors.add(ValidationError.INVALID_PRICE)
            status = ValidationStatus.INVALID
        } else if (priceVal < 0) {
            errors.add(ValidationError.NEGATIVE_PRICE)
            status = ValidationStatus.INVALID
        }

        outList.add(
            DraftItem(
                draftItemId      = "item-${java.util.UUID.randomUUID()}",
                categoryName     = category,
                productName      = name,
                description      = description,
                unit             = unit,
                priceText        = priceRaw,
                price            = priceVal,
                source           = ImportSource.EXCEL_FILE,
                sourceRowNumber  = rowNum,
                originalLine     = "Row $rowNum: ${cells.joinToString(" | ")}",
                validationStatus = status,
                validationErrors = errors
            )
        )
    }

    private fun safeCell(cells: List<String>, colIndex: Int): String =
        if (colIndex >= 0) cells.getOrNull(colIndex)?.trim() ?: "" else ""
}
